-- Active: 1672694681625@@127.0.0.1@3306@Ayrshop
DROP SCHEMA IF EXISTS Ayrshop;
CREATE SCHEMA IF NOT EXISTS Ayrshop;

CREATE TABLE Ayrshop.users (
  id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  experience INTEGER NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE Ayrshop.orders (
  id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  userId INTEGER NOT NULL,
  productId INTEGER NOT NULL,
  FOREIGN KEY (userId) REFERENCES Ayrshop.users(id)
);
